import 'exercise_entity.dart';

class ExerciseCatalog {
  static final List<ExerciseEntity> defaultExercises = [
    // 🏋️ CHEST
    const ExerciseEntity(
      id: 'ex-chest-1',
      name: 'Flat Barbell Bench Press',
      category: ExerciseCategory.chest,
      equipment: 'Barbell',
      target: 'Mid Pectorals, Anterior Delts, Triceps',
      description: 'The premier compound chest exercise for raw power and mass.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-2',
      name: 'Incline Dumbbell Press',
      category: ExerciseCategory.chest,
      equipment: 'Dumbbells',
      target: 'Upper Clavicular Pectoralis',
      description: '30-45 degree incline pressing to build upper chest shelf.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-3',
      name: 'Flat Dumbbell Press',
      category: ExerciseCategory.chest,
      equipment: 'Dumbbells',
      target: 'Pectoralis Major',
      description: 'Greater range of motion and stabilizer activation than barbell.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-4',
      name: 'Incline Barbell Bench Press',
      category: ExerciseCategory.chest,
      equipment: 'Barbell',
      target: 'Upper Chest & Front Deltoids',
      description: 'Heavy compound upper chest pressing.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-5',
      name: 'Cable Chest Flyes',
      category: ExerciseCategory.chest,
      equipment: 'Cable',
      target: 'Inner & Sternal Pectoralis',
      description: 'Constant resistance through peak chest contraction.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-6',
      name: 'Dumbbell Chest Flyes',
      category: ExerciseCategory.chest,
      equipment: 'Dumbbells',
      target: 'Outer & Lower Chest Stretch',
      description: 'Deep stretch isolation fly on flat bench.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-7',
      name: 'Push-Ups (Bodyweight)',
      category: ExerciseCategory.chest,
      equipment: 'Bodyweight',
      target: 'Pectorals, Triceps, Core',
      description: 'Classic calisthenic chest and core baseline.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-8',
      name: 'Chest Dips',
      category: ExerciseCategory.chest,
      equipment: 'Parallel Bars',
      target: 'Lower Pectoralis & Triceps',
      description: 'Forward torso lean dips for massive lower chest flare.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-9',
      name: 'Decline Barbell Bench Press',
      category: ExerciseCategory.chest,
      equipment: 'Barbell',
      target: 'Lower Pectoralis Major',
      description: 'Reduced shoulder stress pressing targeting lower chest.',
    ),
    const ExerciseEntity(
      id: 'ex-chest-10',
      name: 'Dumbbell Pullover',
      category: ExerciseCategory.chest,
      equipment: 'Dumbbell',
      target: 'Serratus, Chest & Lats',
      description: 'Cross-bench pullover expanding ribcage and chest.',
    ),

    // 🚣 BACK
    const ExerciseEntity(
      id: 'ex-back-1',
      name: 'Barbell Deadlift',
      category: ExerciseCategory.back,
      equipment: 'Barbell',
      target: 'Posterior Chain, Erectors, Lats, Traps',
      description: 'The king of pulling exercises for total back thickness.',
    ),
    const ExerciseEntity(
      id: 'ex-back-2',
      name: 'Lat Pulldown',
      category: ExerciseCategory.back,
      equipment: 'Cable',
      target: 'Latissimus Dorsi (Width)',
      description: 'Vertical cable pull for V-taper lat development.',
    ),
    const ExerciseEntity(
      id: 'ex-back-3',
      name: 'Seated Cable Row',
      category: ExerciseCategory.back,
      equipment: 'Cable',
      target: 'Rhomboids, Mid-Back, Lower Lats',
      description: 'Horizontal rowing for mid-back thickness and posture.',
    ),
    const ExerciseEntity(
      id: 'ex-back-4',
      name: 'Barbell Bent-Over Row',
      category: ExerciseCategory.back,
      equipment: 'Barbell',
      target: 'Total Lats & Rhomboids',
      description: 'Heavy 45-degree row for back density.',
    ),
    const ExerciseEntity(
      id: 'ex-back-5',
      name: 'Single-Arm Dumbbell Row',
      category: ExerciseCategory.back,
      equipment: 'Dumbbell',
      target: 'Lats & Rotators',
      description: 'Unilateral back drive eliminating muscle imbalances.',
    ),
    const ExerciseEntity(
      id: 'ex-back-6',
      name: 'Pull-Ups / Chin-Ups',
      category: ExerciseCategory.back,
      equipment: 'Pull-Up Bar',
      target: 'Lats, Upper Back, Biceps',
      description: 'Bodyweight vertical pulling benchmark.',
    ),
    const ExerciseEntity(
      id: 'ex-back-7',
      name: 'T-Bar Row',
      category: ExerciseCategory.back,
      equipment: 'T-Bar / Machine',
      target: 'Mid Back & Upper Lats',
      description: 'Supported heavy rowing for mid-back thickness.',
    ),
    const ExerciseEntity(
      id: 'ex-back-8',
      name: 'Face Pulls',
      category: ExerciseCategory.back,
      equipment: 'Cable Rope',
      target: 'Rear Delts, Rotator Cuff, Traps',
      description: 'Essential shoulder health and upper back postural pull.',
    ),
    const ExerciseEntity(
      id: 'ex-back-9',
      name: 'Straight-Arm Lat Pulldown',
      category: ExerciseCategory.back,
      equipment: 'Cable',
      target: 'Lat Isolation & Serratus',
      description: 'Pure lat sweep isolation without bicep fatigue.',
    ),

    // 🦵 LEGS
    const ExerciseEntity(
      id: 'ex-legs-1',
      name: 'Barbell Back Squat',
      category: ExerciseCategory.legs,
      equipment: 'Barbell',
      target: 'Quadriceps, Glutes, Adductors',
      description: 'The foundation of lower body strength and mass.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-2',
      name: 'Romanian Deadlift (RDL)',
      category: ExerciseCategory.legs,
      equipment: 'Barbell / Dumbbells',
      target: 'Hamstrings & Glutes',
      description: 'Hip hinge movement for hamstring stretch and glute tie-in.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-3',
      name: 'Leg Press',
      category: ExerciseCategory.legs,
      equipment: 'Machine',
      target: 'Quadriceps & Glutes',
      description: 'Heavy quad volume without spinal axial loading.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-4',
      name: 'Bulgarian Split Squat',
      category: ExerciseCategory.legs,
      equipment: 'Dumbbells',
      target: 'Single Leg Quad & Glute Drive',
      description: 'Unilateral leg punishment and stabilization.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-5',
      name: 'Barbell Front Squat',
      category: ExerciseCategory.legs,
      equipment: 'Barbell',
      target: 'Quadriceps (Anterior Chain) & Core',
      description: 'Upright torso quad emphasis.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-6',
      name: 'Leg Extension Machine',
      category: ExerciseCategory.legs,
      equipment: 'Machine',
      target: 'Rectus Femoris & Quad Teardrop',
      description: 'Direct quad isolation and peak knee extension.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-7',
      name: 'Lying Leg Curl',
      category: ExerciseCategory.legs,
      equipment: 'Machine',
      target: 'Hamstrings (Knee Flexion)',
      description: 'Isolated hamstring contraction.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-8',
      name: 'Walking Dumbbell Lunges',
      category: ExerciseCategory.legs,
      equipment: 'Dumbbells',
      target: 'Glutes, Quads & Hamstrings',
      description: 'Dynamic unilateral leg builder.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-9',
      name: 'Hack Squat',
      category: ExerciseCategory.legs,
      equipment: 'Machine',
      target: 'Quad Sweep & Outer Thighs',
      description: 'Guided angle quad loading.',
    ),
    const ExerciseEntity(
      id: 'ex-legs-10',
      name: 'Goblet Squat',
      category: ExerciseCategory.legs,
      equipment: 'Kettlebell / Dumbbell',
      target: 'Quads & Hip Mobility',
      description: 'Deep squat pattern ideal for mobility and quad pump.',
    ),

    // 🥥 SHOULDERS
    const ExerciseEntity(
      id: 'ex-sh-1',
      name: 'Overhead Barbell Press (OHP)',
      category: ExerciseCategory.shoulders,
      equipment: 'Barbell',
      target: 'Anterior & Lateral Deltoids, Core',
      description: 'Strict standing press for cannonball shoulders.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-2',
      name: 'Seated Dumbbell Shoulder Press',
      category: ExerciseCategory.shoulders,
      equipment: 'Dumbbells',
      target: 'Front & Side Deltoids',
      description: 'Full range dumbbell pressing with back support.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-3',
      name: 'Dumbbell Lateral Raise',
      category: ExerciseCategory.shoulders,
      equipment: 'Dumbbells',
      target: 'Lateral Deltoids (Shoulder Width)',
      description: 'The #1 exercise for creating broad shoulder width.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-4',
      name: 'Cable Lateral Raise',
      category: ExerciseCategory.shoulders,
      equipment: 'Cable',
      target: 'Side Deltoid (Constant Tension)',
      description: 'Constant resistance through the full lateral arc.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-5',
      name: 'Arnold Dumbbell Press',
      category: ExerciseCategory.shoulders,
      equipment: 'Dumbbells',
      target: 'Anterior & Lateral Deltoids',
      description: 'Rotational pressing engaging all three deltoid heads.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-6',
      name: 'Front Dumbbell Raise',
      category: ExerciseCategory.shoulders,
      equipment: 'Dumbbells',
      target: 'Anterior Deltoids',
      description: 'Front delt isolation.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-7',
      name: 'Rear Delt Reverse Flyes',
      category: ExerciseCategory.shoulders,
      equipment: 'Dumbbells / Pec Deck',
      target: 'Posterior Deltoids',
      description: 'Crucial for 3D shoulder shape and balanced posture.',
    ),
    const ExerciseEntity(
      id: 'ex-sh-8',
      name: 'Barbell Upright Row',
      category: ExerciseCategory.shoulders,
      equipment: 'Barbell / EZ Bar',
      target: 'Side Deltoids & Upper Traps',
      description: 'Vertical pulling targeting shoulder caps and traps.',
    ),

    // 💪 BICEPS
    const ExerciseEntity(
      id: 'ex-bi-1',
      name: 'Incline Dumbbell Curl',
      category: ExerciseCategory.biceps,
      equipment: 'Dumbbells',
      target: 'Biceps Long Head (Peak)',
      description: 'Maximal stretch on the long head from seated incline position.',
    ),
    const ExerciseEntity(
      id: 'ex-bi-2',
      name: 'Standing Barbell Bicep Curl',
      category: ExerciseCategory.biceps,
      equipment: 'Barbell / EZ Bar',
      target: 'Overall Bicep Mass',
      description: 'The staple bicep mass builder.',
    ),
    const ExerciseEntity(
      id: 'ex-bi-3',
      name: 'Dumbbell Hammer Curls',
      category: ExerciseCategory.biceps,
      equipment: 'Dumbbells',
      target: 'Brachialis & Brachioradialis',
      description: 'Neutral grip curl for arm thickness and forearm density.',
    ),
    const ExerciseEntity(
      id: 'ex-bi-4',
      name: 'EZ-Bar Preacher Curl',
      category: ExerciseCategory.biceps,
      equipment: 'Preacher Bench & EZ Bar',
      target: 'Biceps Short Head (Width)',
      description: 'Eliminates momentum for strict lower bicep tension.',
    ),
    const ExerciseEntity(
      id: 'ex-bi-5',
      name: 'Concentration Curl',
      category: ExerciseCategory.biceps,
      equipment: 'Dumbbell',
      target: 'Bicep Peak Isolation',
      description: 'Seated inner thigh curl for focused bicep peak contraction.',
    ),
    const ExerciseEntity(
      id: 'ex-bi-6',
      name: 'Cable Bicep Curl',
      category: ExerciseCategory.biceps,
      equipment: 'Cable',
      target: 'Biceps (Constant Tension)',
      description: 'Continuous cable tension throughout the entire curl ROM.',
    ),

    // ⚡ TRICEPS
    const ExerciseEntity(
      id: 'ex-tri-1',
      name: 'Triceps Rope Pushdown',
      category: ExerciseCategory.triceps,
      equipment: 'Cable Rope',
      target: 'Triceps Lateral Head',
      description: 'Rope flare at the bottom for horse-shoe tricep definition.',
    ),
    const ExerciseEntity(
      id: 'ex-tri-2',
      name: 'Overhead Dumbbell Triceps Extension',
      category: ExerciseCategory.triceps,
      equipment: 'Dumbbell',
      target: 'Triceps Long Head (Arm Size)',
      description: 'Deep overhead stretch targeting the largest tricep head.',
    ),
    const ExerciseEntity(
      id: 'ex-tri-3',
      name: 'Skull Crushers (Lying Triceps Extension)',
      category: ExerciseCategory.triceps,
      equipment: 'EZ Bar / Barbell',
      target: 'Triceps Medial & Long Head',
      description: 'Lying extension to forehead for tricep thickness.',
    ),
    const ExerciseEntity(
      id: 'ex-tri-4',
      name: 'Close-Grip Barbell Bench Press',
      category: ExerciseCategory.triceps,
      equipment: 'Barbell',
      target: 'Triceps & Inner Chest',
      description: 'Heavy compound pressing for raw tricep lockout strength.',
    ),
    const ExerciseEntity(
      id: 'ex-tri-5',
      name: 'Parallel Bar Tricep Dips',
      category: ExerciseCategory.triceps,
      equipment: 'Parallel Bars',
      target: 'Total Triceps',
      description: 'Upright torso dips for pure tricep overload.',
    ),
    const ExerciseEntity(
      id: 'ex-tri-6',
      name: 'Cable Straight Bar Pushdown',
      category: ExerciseCategory.triceps,
      equipment: 'Cable Bar',
      target: 'Lateral & Medial Triceps',
      description: 'Heavy pushdown for tricep lockout power.',
    ),

    // 🧘 CORE
    const ExerciseEntity(
      id: 'ex-core-1',
      name: 'Plank with Shoulder Taps',
      category: ExerciseCategory.core,
      equipment: 'Bodyweight',
      target: 'Transverse Abdominis & Obliques',
      description: 'Anti-rotational core stabilization.',
    ),
    const ExerciseEntity(
      id: 'ex-core-2',
      name: 'Hanging Leg / Knee Raises',
      category: ExerciseCategory.core,
      equipment: 'Pull-Up Bar',
      target: 'Lower Rectus Abdominis & Hip Flexors',
      description: 'Hanging core compression and lower abs.',
    ),
    const ExerciseEntity(
      id: 'ex-core-3',
      name: 'Cable Woodchoppers',
      category: ExerciseCategory.core,
      equipment: 'Cable',
      target: 'Internal & External Obliques',
      description: 'Rotational core power and waist taper.',
    ),
    const ExerciseEntity(
      id: 'ex-core-4',
      name: 'Russian Twists',
      category: ExerciseCategory.core,
      equipment: 'Bodyweight / Medicine Ball',
      target: 'Obliques & Core Rotation',
      description: 'Seated rotational twist for rotational athletes.',
    ),
    const ExerciseEntity(
      id: 'ex-core-5',
      name: 'Ab Wheel Rollout',
      category: ExerciseCategory.core,
      equipment: 'Ab Wheel',
      target: 'Total Rectus Abdominis & Core Wall',
      description: 'Extreme anti-extension core challenge.',
    ),
    const ExerciseEntity(
      id: 'ex-core-6',
      name: 'Bicycle Crunches',
      category: ExerciseCategory.core,
      equipment: 'Bodyweight',
      target: 'Upper/Lower Abs & Obliques',
      description: 'Dynamic diagonal core contraction.',
    ),

    // 🍑 GLUTES
    const ExerciseEntity(
      id: 'ex-glu-1',
      name: 'Barbell Hip Thrust',
      category: ExerciseCategory.glutes,
      equipment: 'Barbell & Bench',
      target: 'Gluteus Maximus (Peak Contraction)',
      description: 'The ultimate glute builder for strength and aesthetics.',
    ),
    const ExerciseEntity(
      id: 'ex-glu-2',
      name: 'Cable Glute Kickbacks',
      category: ExerciseCategory.glutes,
      equipment: 'Cable Ankle Strap',
      target: 'Gluteus Maximus & Medius',
      description: 'Isolated kickback for upper glute shelf.',
    ),
    const ExerciseEntity(
      id: 'ex-glu-3',
      name: 'Dumbbell Romanian Deadlift (Glute Focus)',
      category: ExerciseCategory.glutes,
      equipment: 'Dumbbells',
      target: 'Glute-Ham Tie In',
      description: 'Hips-back stretch for glute activation.',
    ),
    const ExerciseEntity(
      id: 'ex-glu-4',
      name: 'Bulgarian Split Squat (Glute Lean)',
      category: ExerciseCategory.glutes,
      equipment: 'Dumbbells',
      target: 'Gluteus Medius & Maximus',
      description: 'Forward torso angle targeting glute recruitment.',
    ),
    const ExerciseEntity(
      id: 'ex-glu-5',
      name: 'Cable Pull-Through',
      category: ExerciseCategory.glutes,
      equipment: 'Cable Rope',
      target: 'Glutes & Hamstrings',
      description: 'Pure hip hinge with horizontal cable load.',
    ),

    // 🥋 FOREARMS
    const ExerciseEntity(
      id: 'ex-fa-1',
      name: 'Barbell Wrist Curls',
      category: ExerciseCategory.forearms,
      equipment: 'Barbell',
      target: 'Wrist Flexors (Inner Forearm)',
      description: 'Seated bench wrist flexion for forearm mass.',
    ),
    const ExerciseEntity(
      id: 'ex-fa-2',
      name: 'Reverse Barbell Curls',
      category: ExerciseCategory.forearms,
      equipment: 'Barbell / EZ Bar',
      target: 'Brachioradialis (Top Forearm)',
      description: 'Overhand curl for top forearm and grip strength.',
    ),
    const ExerciseEntity(
      id: 'ex-fa-3',
      name: 'Farmer’s Walk Heavy Carry',
      category: ExerciseCategory.forearms,
      equipment: 'Dumbbells / Trap Bar',
      target: 'Crushing Grip & Forearm Endurance',
      description: 'Heavy isometric walk for grip strength and forearms.',
    ),

    // 🏃 CALVES
    const ExerciseEntity(
      id: 'ex-calf-1',
      name: 'Standing Machine Calf Raise',
      category: ExerciseCategory.calves,
      equipment: 'Machine',
      target: 'Gastrocnemius (Diamond Shape)',
      description: 'Straight knee calf raise for diamond calf shape.',
    ),
    const ExerciseEntity(
      id: 'ex-calf-2',
      name: 'Seated Calf Raise',
      category: ExerciseCategory.calves,
      equipment: 'Machine',
      target: 'Soleus (Lower Calf Width)',
      description: 'Bent knee raise for lower calf thickness.',
    ),
    const ExerciseEntity(
      id: 'ex-calf-3',
      name: 'Leg Press Calf Press',
      category: ExerciseCategory.calves,
      equipment: 'Leg Press Machine',
      target: 'Total Calves & Plantar Flexion',
      description: 'Deep stretch toe press on leg press platform.',
    ),

    // 🤸 HIPS
    const ExerciseEntity(
      id: 'ex-hip-1',
      name: '90-90 Hip Mobility Flow',
      category: ExerciseCategory.hips,
      equipment: 'Bodyweight',
      target: 'Internal & External Hip Rotators',
      description: 'Hip opener sequence to restore squat depth and prevent pain.',
    ),
    const ExerciseEntity(
      id: 'ex-hip-2',
      name: 'Seated Hip Abduction Machine',
      category: ExerciseCategory.hips,
      equipment: 'Machine',
      target: 'Tensor Fasciae Latae & Glute Medius',
      description: 'Outer hip isolation for stabilization.',
    ),
    const ExerciseEntity(
      id: 'ex-hip-3',
      name: 'Seated Hip Adduction Machine',
      category: ExerciseCategory.hips,
      equipment: 'Machine',
      target: 'Inner Thighs & Adductor Longus',
      description: 'Inner thigh strength and groin resilience.',
    ),

    // 🔥 FULL BODY
    const ExerciseEntity(
      id: 'ex-fb-1',
      name: 'Kettlebell Clean & Press',
      category: ExerciseCategory.fullBody,
      equipment: 'Kettlebell',
      target: 'Total Body Triple Extension & Shoulders',
      description: 'Explosive functional compound movement.',
    ),
    const ExerciseEntity(
      id: 'ex-fb-2',
      name: 'Kettlebell Swings',
      category: ExerciseCategory.fullBody,
      equipment: 'Kettlebell',
      target: 'Posterior Chain & Cardiovascular Power',
      description: 'Explosive hip hinge for power and conditioning.',
    ),
    const ExerciseEntity(
      id: 'ex-fb-3',
      name: 'Burpee Box Jump Overs',
      category: ExerciseCategory.fullBody,
      equipment: 'Plyo Box',
      target: 'Cardio, Chest, Quads & Explosive Power',
      description: 'High-intensity conditioning benchmark.',
    ),
    const ExerciseEntity(
      id: 'ex-fb-4',
      name: 'Dumbbell Thrusters (Squat to Press)',
      category: ExerciseCategory.fullBody,
      equipment: 'Dumbbells',
      target: 'Quads, Core & Shoulders',
      description: 'Full body squat to overhead press combination.',
    ),
  ];

  static List<ExerciseEntity> getExercisesForCategory(ExerciseCategory category) {
    return defaultExercises.where((e) => e.category == category).toList();
  }
}
